[package]
name = "hashing"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ring = "0.14.6"

[target.'cfg(target_arch = "wasm32")'.dependencies]
sha2 = "0.8.0"

[dev-dependencies]
rustc-hex = "2.0.1"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.2.47"
